appCar/routes.py
import re
from config import db
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.model_pessoa import Pessoa
from models.model_empresa import Empresa
from models.model_veiculo import Veiculo
from datetime import datetime

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    return render_template('index.html')

@main_bp.route('/cadastrarPessoa', methods=['GET', 'POST'])
def cadastrarPessoa():
    cnh_categorias = { 'A': request.form.get('cnh_categA'), 
                       'B': request.form.get('cnh_categB'),
                       'C': request.form.get('cnh_categC'), 
                       'D': request.form.get('cnh_categD'), 
                       'E': request.form.get('cnh_categE')
    }
    categorias_concatenadas = '|'.join([categoria for categoria, valor in cnh_categorias.items() if valor])  # Usado para ler dic e retorna lista concatena com pipe
    
    if request.method == 'POST':
        nome = request.form['nome']
        cpf = request.form['cpf']
        cpf = re.sub(r'\D', '', cpf)  # Remover pontos e traços do CPF
        data_nascimento = request.form['data_nascimento']
        cnh_categ = categorias_concatenadas
        cnh = request.form['cnh'][:9]  # Garantir que o CNH tenha no máximo 9 caracteres
        data_vencimento_cnh = request.form['data_vencimento_cnh']
        cep  = request.form['cep']
        rua  = request.form['rua']
        numero  = request.form['numero']
        bairro  = request.form['bairro']
        cidade  = request.form['cidade']
        estado  = request.form['estado']
        email = request.form['email']
        telefone = request.form['telefone']
        
        pessoa_cpf = Pessoa.query.filter_by(cpf=cpf).first()
        pessoa_cnh = Pessoa.query.filter_by(cnh=cnh).first()
        
        if pessoa_cpf:
            flash('CPF já cadastrado. Por favor, verifique o número e tente novamente.', 'danger')
            return render_template('pessoa/cadastrarPessoa.html', 
                                   nome=nome, 
                                   cpf=cpf, 
                                   data_nascimento=data_nascimento,
                                   cnh_categ=cnh_categ, 
                                   cnh=cnh,
                                   data_vencimento_cnh=data_vencimento_cnh,
                                   cep=cep,
                                   rua=rua,
                                   numero=numero,
                                   bairro=bairro,
                                   cidade=cidade,
                                   estado=estado,
                                   email=email,
                                   telefone=telefone
                                   )
        elif pessoa_cnh:
            flash('CNH já cadastrada. Por favor, verifique o número e tente novamente.', 'danger')
            return render_template('pessoa/cadastrarPessoa.html',
                                   nome=nome, 
                                   cpf=cpf, 
                                   data_nascimento=data_nascimento,
                                   cnh_categ=cnh_categ, 
                                   cnh=cnh,
                                   data_vencimento_cnh=data_vencimento_cnh,
                                   cep=cep,
                                   rua=rua,
                                   numero=numero,
                                   bairro=bairro,
                                   cidade=cidade,
                                   estado=estado,
                                   email=email,
                                   telefone=telefone
                                   )
        else:
            nova_pessoa = Pessoa(
                nome=nome,
                cpf=cpf,
                data_nascimento=data_nascimento,
                cnh_categ=cnh_categ,
                cnh=cnh,
                data_vencimento_cnh=data_vencimento_cnh,
                cep=cep,
                rua=rua,
                numero=numero,
                bairro=bairro,
                cidade=cidade,
                estado=estado,
                email=email,
                telefone=telefone
            )
            db.session.add(nova_pessoa)
            db.session.commit()
            flash('Pessoa cadastrada com sucesso!', 'success')
            return redirect(url_for('main.consultarPessoa'))
    
    return render_template('pessoa/cadastrarPessoa.html')

@main_bp.route('/consultarPessoa')
def consultarPessoa():
    pessoas = Pessoa.query.all()
    if not pessoas:
        flash('Não há dados', 'danger')
        return render_template('index.html')
    hoje = datetime.today().date()  # Data atual como datetime.date
    
    return render_template('pessoa/consultarPessoa.html', pessoas=pessoas, hoje=hoje)

@main_bp.route('/editarPessoa/<int:id>', methods=['GET', 'POST'])
def editarPessoa(id):
    pessoa = Pessoa.query.get_or_404(id)
    
    cnh_categorias = { 'A': request.form.get('cnh_categA'), 
                       'B': request.form.get('cnh_categB'),
                       'C': request.form.get('cnh_categC'), 
                       'D': request.form.get('cnh_categD'), 
                       'E': request.form.get('cnh_categE')
    }
    categorias_concatenadas = '-'.join([categoria for categoria, valor in cnh_categorias.items() if valor])
    
    if request.method == 'POST':
        pessoa.nome = request.form['nome']
        pessoa.cpf = request.form['cpf']
        pessoa.cpf = re.sub(r'\D', '', pessoa.cpf)  # Remover pontos e traços do CPF
        pessoa.data_nascimento = request.form['data_nascimento']
        pessoa.cnh_categ = categorias_concatenadas
        pessoa.cnh = request.form['cnh'][:9]  # Garantir que o CNH tenha no máximo 9 caracteres
        pessoa.data_vencimento_cnh = request.form['data_vencimento_cnh']
        db.session.commit()
        return redirect(url_for('main.consultarPessoa'))
    
    return render_template('pessoa/editarPessoa.html', pessoa=pessoa)

@main_bp.route('/deletarPessoa/<int:id>')
def deletarPessoa(id):
    pessoa = Pessoa.query.get_or_404(id)
    cpf = pessoa.cpf
    db.session.delete(pessoa)
    db.session.commit()
    flash(f'O CPF:{cpf} foi deletado com sucesso!', 'success')
    return redirect(url_for('main.consultarPessoa'))

@main_bp.route('/testar')
def testar():
    return render_template('pessoa/teste.html')

@main_bp.route('/resultado', methods=['GET', 'POST'])
def resultado():
    chek1 = request.form.get('nameA')
    chek2 = request.form.get('nameB')
    return render_template('pessoa/resultado.html', valor1=chek1, valor2=chek2)

@main_bp.route('/cadastrarEmpresa', methods=['GET', 'POST'])
def cadastrarEmpresa():
    if request.method == 'POST':
        nome = request.form['nome']
        cnpj = request.form['cnpj']
        cnpj = re.sub(r'\D', '', cnpj)  # Remover pontos e traços do CNPJ
        cep = request.form['cep']
        rua = request.form['rua']
        numero = request.form['numero']
        bairro = request.form['bairro']
        cidade = request.form['cidade']
        estado = request.form['estado']
        email = request.form['email']
        telefone = request.form['telefone']

        empresa_cnpj = Empresa.query.filter_by(cnpj=cnpj).first()

        if empresa_cnpj: 
            flash('CNPJ já cadastrado. Por favor, verifique o número e tente novamente.', 'danger')
            return render_template('empresa/cadastrarEmpresa.html', 
                                   nome=nome, 
                                   cnpj=cnpj, 
                                   cep=cep,
                                   rua=rua,
                                   numero=numero,
                                   bairro=bairro,
                                   cidade=cidade,
                                   estado=estado,
                                   email=email,
                                   telefone=telefone
                                   )
        else:
            nova_empresa = Empresa(
                nome=nome,
                cnpj=cnpj,
                cep=cep,
                rua=rua,
                numero=numero,
                bairro=bairro,
                cidade=cidade,
                estado=estado,
                email=email,
                telefone=telefone
            )
            db.session.add(nova_empresa)
            db.session.commit()
            flash('Empresa cadastrada com sucesso!', 'success')
            return redirect(url_for('main.consultarEmpresa'))

    return render_template('empresa/cadastrarEmpresa.html')


@main_bp.route('/consultarEmpresa')
def consultarEmpresa():
    empresas = Empresa.query.all()
    if not empresas:
        flash('Não há dados', 'danger')
        return render_template('index.html')
    hoje = datetime.today().date()  # Data atual como datetime.date
    
    return render_template('empresa/consultarEmpresa.html', empresas=empresas, hoje=hoje)



@main_bp.route('/editarEmpresa/<int:id>', methods=['GET', 'POST'])
def editarEmpresa(id):
    empresa = Empresa.query.get_or_404(id)      
    if request.method == 'POST':
        empresa.nome = request.form['nome']
        empresa.cnpj = request.form['cnpj']
        empresa.cnpj = re.sub(r'\D', '', empresa.cnpj)  # Remover pontos e traços do CPF
        empresa.cep = request.form['cep']
        empresa.rua =  request.form['rua']
        empresa.estado = request.form['estado']
        empresa.cidade = request.form['cidade']
        empresa.numero = request.form['numero']
        empresa.bairro = request.form['bairro']
        empresa.email = request.form['email']
        empresa.telefone = request.form['telefone']
        db.session.commit()
        return redirect(url_for('main.consultarEmpresa'))
    
    return render_template('empresa/editarEmpresa.html', empresa=empresa)


@main_bp.route('/deletarEmpresa/<int:id>')
def deletarEmpresa(id):

appCar/templates/pessoa/cadastrarPessoa.html
{% extends "base.html" %}

{% block title %}Cadastrar{% endblock %}

{% block content %}
<div class="container-fluid">
    <h1>Cadastrar Pessoa</h1>
    
    <h2>Dados Pessoais</h2>
    <form method="POST" action="{{ url_for('main.cadastrarPessoa') }}">
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="nome">Nome:</label>
                <input type="text" class="form-control" id="nome" name="nome" value="{{ request.form['nome'] if request.form.get('nome') else nome }}" required>
            </div>
            <div class="form-group col-md-6">
                <label for="cpf">CPF:</label>
                <input type="text" class="form-control" id="cpf" name="cpf" value="{{ request.form['cpf'] if request.form.get('cpf') else cpf }}" required>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="data_nascimento">Data de Nascimento:</label>
                <input type="date" class="form-control" id="data_nascimento" name="data_nascimento" value="{{ request.form['data_nascimento'] if request.form.get('data_nascimento') else data_nascimento }}" required>
            </div>
        </div>

        <hr>

        <h2>Endereço</h2>
        <div class="form-row">
            <div class="form-group col-md-3">
                <label for="cep">CEP:</label>
                <input type="text" class="form-control" id="cep" name="cep" value="{{ request.form['cep'] if request.form.get('cep') else cep }}" required>
            </div>
            <div class="form-group col-md-6">
                <label for="rua">Rua:</label>
                <input type="text" class="form-control" id="rua" name="rua" value="{{ request.form['rua'] if request.form.get('rua') else rua }}" required>
            </div>
            <div class="form-group col-md-3">
                <label for="numero">Número:</label>
                <input type="text" class="form-control" id="numero" name="numero" value="{{ request.form['numero'] if request.form.get('numero') else numero }}" required>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="bairro">Bairro:</label>
                <input type="text" class="form-control" id="bairro" name="bairro" value="{{ request.form['bairro'] if request.form.get('bairro') else bairro }}" required>
            </div>
            <div class="form-group col-md-6">
                <label for="cidade_estado">Cidade:</label>
                <input type="text" class="form-control" id="cidade" name="cidade" value="{{ request.form['cidade'] if request.form.get('cidade') else cidade }}" required>
            </div>
            <div class="form-group col-md-6">
                <label for="cidade_estado">Estado:</label>
                <input type="text" class="form-control" id="estado" name="estado" value="{{ request.form['estado'] if request.form.get('estado') else estado }}" required>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="email">Email:</label>
                <input type="email" class="form-control" id="email" name="email" value="{{ request.form['email'] if request.form.get('email') else email }}" required>
            </div>
            <div class="form-group col-md-6">
                <label for="celular">Celular:</label>
                <input type="text" class="form-control" id="celular" name="celular" value="{{ request.form['celular'] if request.form.get('celular') else celular }}" required>
            </div>
        </div>

        <hr>

        <h2>Documentos</h2>
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="cnh">CNH:</label>
                <input type="text" class="form-control" id="cnh" name="cnh" value="{{ request.form['cnh'] if request.form.get('cnh') else cnh }}" required>
            </div>
            <div class="form-group col-md-4">
                <label for="cnh_categ">Categoria CNH:</label>
                <div class="form-group">
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" name="cnh_categA" value="A" id="cnh_A">
                        <label class="form-check-label" for="cnh_A">A</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" name="cnh_categB" value="B" id="cnh_B">
                        <label class="form-check-label" for="cnh_B">B</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" name="cnh_categC" value="C" id="cnh_C">
                        <label class="form-check-label" for="cnh_C">C</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" name="cnh_cateD" value="D" id="cnh_D">
                        <label class="form-check-label" for="cnh_D">D</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" name="cnh_categE" value="E" id="cnh_E">
                        <label class="form-check-label" for="cnh_E">E</label>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-4">
                <label for="data_vencimento_cnh">Validade:</label>
                <input type="date" class="form-control" id="data_vencimento_cnh" name="data_vencimento_cnh" value="{{ request.form['data_vencimento_cnh'] if request.form.get('data_vencimento_cnh') else data_vencimento_cnh }}" required>
            </div>
        </div>

        <hr>
        
        

        <button type="submit" class="btn btn-primary">Cadastrar</button>
    </form>
</div>
{% endblock %}

appCar/templates/pessoa/consultarPessoa.html
{% extends "base.html" %}

{% block title %}Consulta Pessoa{% endblock %}

{% block content %}
    <h1>Consulta Pessoas</h1>
    <table class="table table-striped me-auto mb-2 mb-lg-0" >
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>CNH</th>
                <th>Vencimento CNH</th>
                <th>Data atual</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for pessoa in pessoas %}
            <tr class="{% if pessoa.data_vencimento_cnh <= hoje %}table-danger{% endif %}">
                <td>{{ pessoa.id }}</td>
                <td>{{ pessoa.nome }}</td>
                <td>{{ pessoa.cpf }}</td>
                <td>{{ pessoa.cnh_categ }}</td>
                <td>{{ pessoa.data_vencimento_cnh.strftime('%d/%m/%Y') }}</td>
                <td>{{ hoje.strftime('%d/%m/%Y') }}</td>
                <td>
                    <a href="{{ url_for('main.editarPessoa', id=pessoa.id) }}" class="btn btn-warning btn-sm">Editar</a>
                    <a href="{{ url_for('main.deletarPessoa', id=pessoa.id) }}" class="btn btn-danger btn-sm">Deletar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

appCar/templates/pessoa/editarPessoa.html
{% extends "base.html" %}

{% block title %}Editar Pessoa{% endblock %}

{% block content %}
    <h1>Editar Pessoa</h1>
    <form method="POST" action="{{ url_for('main.editarPessoa', id=pessoa.id) }}">
        <div class="form-group">
            <label for="nome">Nome:</label>
            <input type="text" class="form-control" id="nome" name="nome" value="{{ pessoa.nome }}" required>
        </div>
        <div class="form-group">
            <label for="cpf">CPF:</label>
            <input type="text" class="form-control" id="cpf" name="cpf" value="{{ pessoa.cpf }}" required>
        </div>
        <div class="form-group">
            <label for="data_nascimento">Data de Nascimento:</label>
            <input type="date" class="form-control" id="data_nascimento" name="data_nascimento"   value="{{ pessoa.data_nascimento }}" required>
        </div>
        <div class="form-group col-md-4">
            <div>
                <label for="cnh_categ">Categoria CNH Atual: <strong>{{ pessoa.cnh_categ}}</strong>  </label>

            </div>
            <div class="form-group">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="cnh_categA" value="A" id="cnh_A">
                    <label class="form-check-label" for="cnh_A">A</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="cnh_categB" value="B" id="cnh_B">
                    <label class="form-check-label" for="cnh_B">B</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="cnh_categC" value="C" id="cnh_C">
                    <label class="form-check-label" for="cnh_C">C</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="cnh_categD" value="D" id="cnh_D">
                    <label class="form-check-label" for="cnh_D">D</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="cnh_categE" value="E" id="cnh_E">
                    <label class="form-check-label" for="cnh_E">E</label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="cnh">Numero CNH:</label>
            <input type="text" class="form-control" id="cnh" name="cnh" value="{{ pessoa.cnh }}" required>
        </div>
        <div class="form-group">
            <label for="data_vencimento_cnh">Vencimento cnh:</label>
            <input type="date" class="form-control" id="data_vencimento_cnh" name="data_vencimento_cnh" value="{{ pessoa.data_vencimento_cnh }}"  required>
        </div>





        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
{% endblock %}

appCar/templates/pessoa/excluirPessoa.html
{% extends "base.html" %}

{% block title %}Excluir Pessoa{% endblock %}

{% block content %}
    
    <!-- Modal -->
    <div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Confirmar Deleção</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Tem certeza que deseja deletar esta pessoa?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <a id="deleteButton" href="#" class="btn btn-danger">Deletar</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

<!-- JavaScript -->
<script>
    function confirmDelete(id) {
        var deleteButton = document.getElementById('deleteButton');
        deleteButton.href = "{{ url_for('deletar', id='') }}" + id;
        $('#confirmModal').modal('show');
    }
</script>

{% endblock %}