appCar/routes.py
import re
from config import db
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.model_pessoa import Pessoa
from models.model_empresa import Empresa
from models.model_veiculo import Veiculo
from datetime import datetime

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    return render_template('index.html')

@main_bp.route('/cadastrarPessoa', methods=['GET', 'POST'])
def cadastrarPessoa():
    cnh_categorias = { 'A': request.form.get('cnh_categA'), 
                       'B': request.form.get('cnh_categB'),
                       'C': request.form.get('cnh_categC'), 
                       'D': request.form.get('cnh_categD'), 
                       'E': request.form.get('cnh_categE')
    }
    categorias_concatenadas = '|'.join([categoria for categoria, valor in cnh_categorias.items() if valor])  # Usado para ler dic e retorna lista concatena com pipe
    
    if request.method == 'POST':
        nome = request.form['nome']
        cpf = request.form['cpf']
        cpf = re.sub(r'\D', '', cpf)  # Remover pontos e traços do CPF
        data_nascimento = request.form['data_nascimento']
        cnh_categ = categorias_concatenadas
        cnh = request.form['cnh'][:9]  # Garantir que o CNH tenha no máximo 9 caracteres
        data_vencimento_cnh = request.form['data_vencimento_cnh']
        cep  = request.form['cep']
        rua  = request.form['rua']
        numero  = request.form['numero']
        bairro  = request.form['bairro']
        cidade  = request.form['cidade']
        estado  = request.form['estado']
        email = request.form['email']
        telefone = request.form['telefone']
        
        pessoa_cpf = Pessoa.query.filter_by(cpf=cpf).first()
        pessoa_cnh = Pessoa.query.filter_by(cnh=cnh).first()
        
        if pessoa_cpf:
            flash('CPF já cadastrado. Por favor, verifique o número e tente novamente.', 'danger')
            return render_template('pessoa/cadastrarPessoa.html', 
                                   nome=nome, 
                                   cpf=cpf, 
                                   data_nascimento=data_nascimento,
                                   cnh_categ=cnh_categ, 
                                   cnh=cnh,
                                   data_vencimento_cnh=data_vencimento_cnh,
                                   cep=cep,
                                   rua=rua,
                                   numero=numero,
                                   bairro=bairro,
                                   cidade=cidade,
                                   estado=estado,
                                   email=email,
                                   telefone=telefone
                                   )
        elif pessoa_cnh:
            flash('CNH já cadastrada. Por favor, verifique o número e tente novamente.', 'danger')
            return render_template('pessoa/cadastrarPessoa.html',
                                   nome=nome, 
                                   cpf=cpf, 
                                   data_nascimento=data_nascimento,
                                   cnh_categ=cnh_categ, 
                                   cnh=cnh,
                                   data_vencimento_cnh=data_vencimento_cnh,
                                   cep=cep,
                                   rua=rua,
                                   numero=numero,
                                   bairro=bairro,
                                   cidade=cidade,
                                   estado=estado,
                                   email=email,
                                   telefone=telefone
                                   )
        else:
            nova_pessoa = Pessoa(
                nome=nome,
                cpf=cpf,
                data_nascimento=data_nascimento,
                cnh_categ=cnh_categ,
                cnh=cnh,
                data_vencimento_cnh=data_vencimento_cnh,
                cep=cep,
                rua=rua,
                numero=numero,
                bairro=bairro,
                cidade=cidade,
                estado=estado,
                email=email,
                telefone=telefone
            )
            db.session.add(nova_pessoa)
            db.session.commit()
            flash('Pessoa cadastrada com sucesso!', 'success')
            return redirect(url_for('main.consultarPessoa'))
    
    return render_template('pessoa/cadastrarPessoa.html')

@main_bp.route('/consultarPessoa')
def consultarPessoa():
    pessoas = Pessoa.query.all()
    if not pessoas:
        flash('Não há dados', 'danger')
        return render_template('index.html')
    hoje = datetime.today().date()  # Data atual como datetime.date
    
    return render_template('pessoa/consultarPessoa.html', pessoas=pessoas, hoje=hoje)

@main_bp.route('/editarPessoa/<int:id>', methods=['GET', 'POST'])
def editarPessoa(id):
    pessoa = Pessoa.query.get_or_404(id)
    
    cnh_categorias = { 'A': request.form.get('cnh_categA'), 
                       'B': request.form.get('cnh_categB'),
                       'C': request.form.get('cnh_categC'), 
                       'D': request.form.get('cnh_categD'), 
                       'E': request.form.get('cnh_categE')
    }
    categorias_concatenadas = '-'.join([categoria for categoria, valor in cnh_categorias.items() if valor])
    
    if request.method == 'POST':
        pessoa.nome = request.form['nome']
        pessoa.cpf = request.form['cpf']
        pessoa.cpf = re.sub(r'\D', '', pessoa.cpf)  # Remover pontos e traços do CPF
        pessoa.data_nascimento = request.form['data_nascimento']
        pessoa.cnh_categ = categorias_concatenadas
        pessoa.cnh = request.form['cnh'][:9]  # Garantir que o CNH tenha no máximo 9 caracteres
        pessoa.data_vencimento_cnh = request.form['data_vencimento_cnh']
        db.session.commit()
        return redirect(url_for('main.consultarPessoa'))
    
    return render_template('pessoa/editarPessoa.html', pessoa=pessoa)

@main_bp.route('/deletarPessoa/<int:id>')
def deletarPessoa(id):
    pessoa = Pessoa.query.get_or_404(id)
    cpf = pessoa.cpf
    db.session.delete(pessoa)
    db.session.commit()
    flash(f'O CPF:{cpf} foi deletado com sucesso!', 'success')
    return redirect(url_for('main.consultarPessoa'))

@main_bp.route('/testar')
def testar():
    return render_template('pessoa/teste.html')

@main_bp.route('/resultado', methods=['GET', 'POST'])
def resultado():
    chek1 = request.form.get('nameA')
    chek2 = request.form.get('nameB')
    return render_template('pessoa/resultado.html', valor1=chek1, valor2=chek2)

@main_bp.route('/cadastrarEmpresa', methods=['GET', 'POST'])
def cadastrarEmpresa():
    if request.method == 'POST':
        nome = request.form['nome']
        cnpj = request.form['cnpj']
        cnpj = re.sub(r'\D', '', cnpj)  # Remover pontos e traços do CNPJ
        cep = request.form['cep']
        rua = request.form['rua']
        numero = request.form['numero']
        bairro = request.form['bairro']
        cidade = request.form['cidade']
        estado = request.form['estado']
        email = request.form['email']
        telefone = request.form['telefone']

        empresa_cnpj = Empresa.query.filter_by(cnpj=cnpj).first()

        if empresa_cnpj: 
            flash('CNPJ já cadastrado. Por favor, verifique o número e tente novamente.', 'danger')
            return render_template('empresa/cadastrarEmpresa.html', 
                                   nome=nome, 
                                   cnpj=cnpj, 
                                   cep=cep,
                                   rua=rua,
                                   numero=numero,
                                   bairro=bairro,
                                   cidade=cidade,
                                   estado=estado,
                                   email=email,
                                   telefone=telefone
                                   )
        else:
            nova_empresa = Empresa(
                nome=nome,
                cnpj=cnpj,
                cep=cep,
                rua=rua,
                numero=numero,
                bairro=bairro,
                cidade=cidade,
                estado=estado,
                email=email,
                telefone=telefone
            )
            db.session.add(nova_empresa)
            db.session.commit()
            flash('Empresa cadastrada com sucesso!', 'success')
            return redirect(url_for('main.consultarEmpresa'))

    return render_template('empresa/cadastrarEmpresa.html')


@main_bp.route('/consultarEmpresa')
def consultarEmpresa():
    empresas = Empresa.query.all()
    if not empresas:
        flash('Não há dados', 'danger')
        return render_template('index.html')
    hoje = datetime.today().date()  # Data atual como datetime.date
    
    return render_template('empresa/consultarEmpresa.html', empresas=empresas, hoje=hoje)



@main_bp.route('/editarEmpresa/<int:id>', methods=['GET', 'POST'])
def editarEmpresa(id):
    empresa = Empresa.query.get_or_404(id)      
    if request.method == 'POST':
        empresa.nome = request.form['nome']
        empresa.cnpj = request.form['cnpj']
        empresa.cnpj = re.sub(r'\D', '', empresa.cnpj)  # Remover pontos e traços do CPF
        empresa.cep = request.form['cep']
        empresa.rua =  request.form['rua']
        empresa.estado = request.form['estado']
        empresa.cidade = request.form['cidade']
        empresa.numero = request.form['numero']
        empresa.bairro = request.form['bairro']
        empresa.email = request.form['email']
        empresa.telefone = request.form['telefone']
        db.session.commit()
        return redirect(url_for('main.consultarEmpresa'))
    
    return render_template('empresa/editarEmpresa.html', empresa=empresa)


@main_bp.route('/deletarEmpresa/<int:id>')
def deletarEmpresa(id):

appCar/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Agenda Car{% endblock %}</title>
    <!-- Link CSS do Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Agenda Car</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('main.index') }}">Início</a> 
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Consultar
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{{ url_for('main.consultarPessoa') }}">Pessoas</a> </li>
                  <li><a class="dropdown-item" href="{{ url_for('main.consultarEmpresa') }}">Empresas</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('main.consultarVeiculo') }}">Veiculos</a></li>
               </ul>
               <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Solicitações
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="">Viagens</a></li>
                  <li><a class="dropdown-item" href="#">Diarias</a></li>
               </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Cadastros 
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{{ url_for('main.cadastrarPessoa') }}">Pessoa</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('main.cadastrarEmpresa') }}">Empresa</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('main.cadastrarVeiculo') }}">Veiculos</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{{ url_for('main.testar') }}">Link teste</a></li>
                </ul>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

    <!-- Configuração do flash --> 
    {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} 
    <div class="alert-container"> {% for category, message in messages %} 
    <div class="alert alert-{{ category }} alert-dismissible fade show"
           role="alert"> {{ message }} <button type="button"
                class="btn-close"
                data-bs-dismiss="alert"
                aria-label="Close"/>
      </div> {% endfor %} </div> {% endif %} {% endwith %}

    <!-- Conteúdo da página -->
    <div class="container">
      
        {% block content %}{% endblock %}
    </div>

    <!-- Script JavaScript do Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> 
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script> 
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script> 
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    <script> 
        $(document).ready(function(){ 
            $('#cpf').mask('000.000.000-00'); 
            $('#cnh').mask('000000000'); 
        }); 
    </script>
</body>
</html>

appCar/templates/index.html
{% extends "base.html" %}

{% block title %}Início{% endblock %}

{% block content %}
    <h1>Bem-vindo ao Car Schedule</h1>
    <p>Esta é a página inicial do projeto.</p>
{% endblock %}

appCar/templates/resultado.html
{% extends "base.html" %}

{% block title %}Cadastrar{% endblock %}

{% block content %}






    <h1>Resultado Teste</h1> 
    <p>Valor 1: {{ valor1 }}</p> 
    <p>Valor 2: {{ valor2 }}</p>
   
{% endblock %}

appCar/templates/teste.html
{% extends "base.html" %}

{% block title %}Cadastrar{% endblock %}

{% block content %}
<div class="input-group mb-3">
  <span class="input-group-text" id="basic-addon1">@</span>
  <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
</div>

<div class="input-group mb-3">
  <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2">
  <span class="input-group-text" id="basic-addon2">@example.com</span>
</div>

<label for="basic-url" class="form-label">Your vanity URL</label>
<div class="input-group mb-3">
  <span class="input-group-text" id="basic-addon3">https://example.com/users/</span>
  <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3">
</div>

<div class="input-group mb-3">
  <span class="input-group-text">$</span>
  <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)">
  <span class="input-group-text">.00</span>
</div>

<div class="input-group mb-3">
  <input type="text" class="form-control" placeholder="Username" aria-label="Username">
  <span class="input-group-text">@</span>
  <input type="text" class="form-control" placeholder="Server" aria-label="Server">
</div>

<div class="input-group">
  <span class="input-group-text">With textarea</span>
  <textarea class="form-control" aria-label="With textarea"></textarea>
</div>
{% endblock %}